version: "3.8"

volumes:
  mariadb-data:
services:
  nginx:
    image: tutum/nginx
    ports:
      - "80:80"
    links:
      - phpfpm
    volumes:
      - ${CONFIG_DIR-./config}/nginx/default:/etc/nginx/sites-available/default
      - ${CONFIG_DIR-./config}/nginx/default:/etc/nginx/sites-enabled/default
      - ${LOGS_DIR-./logs}/nginx:/var/log/nginx
  phpfpm:
    image: php:fpmf
    ports:
      - "9000:9000"
    volumes:
      - ${DOCUMENT_ROOT-./public}:/usr/share/nginx/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
      - ${LOGS_DIR-./logs}/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mariadb
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
